packages:
  - "."

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true
strictDepBuilds: true
allowBuilds:
  esbuild: true
  workerd: true
overrides:
  tmp: 0.2.7
  lighthouse: 13.4.1
